name: glova_showcase
description: Glova library showcase app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  eva_color: 1.1.1

  glova:
    path: '../glova'
#    git:
#      url: https://github.com/glovory/glova.git

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
